// One-off: vectorize the TSG mark into SVG outline paths the opening sequence
// can "draw" on stroke-by-stroke. Run: node scripts/trace-logo.mjs
import sharp from 'sharp';
import potrace from 'potrace';
import { writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'public/assets/img/tsg_logo.png');

// Dark artwork sits on a transparent canvas; flatten onto white so potrace sees
// crisp dark shapes against a light background.
const buf = await sharp(SRC).flatten({ background: '#ffffff' }).png().toBuffer();

const svg = await new Promise((resolve, reject) => {
  potrace.trace(
    buf,
    {
      threshold: 165,
      turdSize: 6, // drop specks smaller than this many px
      optTolerance: 0.35,
      turnPolicy: 'minority',
      color: '#0a4d2e',
      background: 'transparent',
    },
    (err, out) => (err ? reject(err) : resolve(out)),
  );
});

const width = Number(svg.match(/width="(\d+)"/)?.[1] ?? 0);
const height = Number(svg.match(/height="(\d+)"/)?.[1] ?? 0);
const d = svg.match(/ d="([^"]+)"/)?.[1] ?? '';
// Each closed contour starts with an absolute M; split so they can be drawn in
// sequence (cap, bandana, lenses, TSG box, letter counters …).
const subpaths = (d.match(/M[^M]*/g) ?? [d]).map((s) => s.trim());

await writeFile(
  join(ROOT, 'src/components/public/home/tsgLogoPaths.ts'),
  `// AUTO-GENERATED by scripts/trace-logo.mjs from public/assets/img/tsg_logo.png.\n` +
    `// Vector outline of the TSG mark; the opening sequence strokes these on to\n` +
    `// "draw" the logo. Regenerate with: node scripts/trace-logo.mjs\n` +
    `export const TSG_LOGO = {\n` +
    `  width: ${width},\n` +
    `  height: ${height},\n` +
    `  paths: ${JSON.stringify(subpaths)},\n` +
    `} as const;\n`,
);

// Visual-check artifacts (deleted after review).
const stroked =
  `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">` +
  `<rect width="100%" height="100%" fill="#f7f4ec"/>` +
  subpaths
    .map((p) => `<path d="${p}" fill="none" stroke="#0a4d2e" stroke-width="3"/>`)
    .join('') +
  `</svg>`;
await sharp(Buffer.from(stroked)).png().toFile(join(ROOT, 'scripts/_logo-preview.png'));

console.log('width', width, 'height', height, 'subpaths', subpaths.length);
